spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.config: DEBUG
