spring:
#  application:
#    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecomendation
      database: fitnessrecomendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 8083

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking



gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: AIzaSyB0Haob7-O_ZPmqEuoGJcNskHP3Mnv3UIg

